fix: Issue 219 nested dataclasses (#220)
Fixes #219 

The previous code 
```python
> ConfigTree(asdict(val))
ConfigTree({'nested_l1_a': False, 'nested_l1_b': {'nested_l2_a': False, 'nested_l2_b': 'default value'}})

```
was initializing the ConfigTree as a flat structure, with the nested
dataclasses as dict, which breaks the expectation of another ConfigTree
at the start of the `__parse` method:

```python
    if is_dataclass(clazz):
        if not isinstance(value, ConfigTree):
            raise TypeConfigException(
                f"expected type {clazz} at {path}, got {type(value)}"
            )
```
This explains the weird error we get in the example.

```python
dataconf.exceptions.TypeConfigException: expected type <class '__main__.L2Nested'> at .top_c.nested_l1_b, got <class 'dict'>
```

The suggested fix uses `ConfigFactory`, which recursively converts
nested dicts to ConfigTrees

```python
> ConfigFactory.from_dict(asdict(val))
ConfigTree({'nested_l1_a': False, 'nested_l1_b': ConfigTree({'nested_l2_a': False, 'nested_l2_b': 'default value'})})

```

---------

Co-authored-by: Hector Romero <hector.romero.rho@gmail.com>